package com.bookease.common.exception;

public enum ErrorCode {
    EMAIL_ALREADY_REGISTERED,
    INVALID_CREDENTIALS,
    INVALID_TOKEN,
    AUTHENTICATION_REQUIRED,
    ACCOUNT_DISABLED,
    VALIDATION_ERROR,
    MALFORMED_REQUEST,
    RESOURCE_NOT_FOUND,
    METHOD_NOT_ALLOWED,
    ACCESS_DENIED,
    INTERNAL_SERVER_ERROR,

    DUPLICATE_CATEGORY,
    CATEGORY_IN_USE,

    PROVIDER_ALREADY_EXISTS,
    INVALID_PROVIDER_STATE,
    PROVIDER_NOT_APPROVED,
    PROVIDER_NOT_AVAILABLE,
    PROVIDER_HAS_APPOINTMENTS,

    DUPLICATE_SERVICE,
    SERVICE_NOT_AVAILABLE,
    INVALID_PROVIDER_SERVICE,

    INVALID_SCHEDULE,
    SCHEDULE_OVERLAP,
    INVALID_BREAK,
    BREAK_OVERLAP,
    BREAK_OUTSIDE_SCHEDULE,

    APPOINTMENT_CONFLICT,
    RESCHEDULE_CONFLICT,
    OUTSIDE_WORKING_HOURS,
    DURING_PROVIDER_BREAK,
    APPOINTMENT_IN_PAST,
    INVALID_APPOINTMENT_STATE,
    APPOINTMENT_ALREADY_CANCELLED,
    APPOINTMENT_ALREADY_COMPLETED,
    SELF_BOOKING_NOT_ALLOWED,

    REMINDER_CONFLICT,
    REMINDER_IN_PAST,
    DUPLICATE_REMINDER
}
